# /etc/ipsec.conf  (OCI Ubuntu VM, StrongSwan 5.9.13)
config setup
    charondebug="cfg 2, knl 2"

conn cloud-to-home
    authby=secret
    auto=add
    keyexchange=ikev2
    # Local side (OCI)
    left=172.16.1.99          # Private IP of the Ubuntu NIC
    leftid=164.152.249.176    # Public IP of OCI
    leftsubnet=172.16.0.0/16
    # Remote side (home)
    right=fameri-lab.ddnsfree.com     # DDNS hostname of the home firewall
    rightid=@fameri-lab.ddnsfree.com
    rightsubnet=10.0.0.0/24
    ike=aes256-sha256-modp2048!
    esp=aes256-sha256!
    dpdaction=restart
    dpddelay=30s
    dpdtimeout=120s
